### ISSUE TITLE
adapt news page

### ISSUE THREAD

**Issue by Roma8642** [NovaDevelopersCo/GregasShop#182]
адаптировать лицевую страницу новости 
![image](https://github.com/NovaDevelopersCo/GregasShop/assets/141335182/a035d511-db9a-4119-9b3c-3cf5311cead5)

**Comment by Roma8642** [comment]
![image](https://github.com/NovaDevelopersCo/GregasShop/assets/141335182/644c37c4-17b3-4f27-829c-eba63b447993)

**Comment by Zoomish** [comment]
Pull request отправил

**Comment by Roma8642** [comment]
![image](https://github.com/NovaDevelopersCo/GregasShop/assets/141335182/611b6306-467e-4e97-a397-ef7451cf8d07)
допилить адаптацию лицевой стр новости
